### ISSUE TITLE
Windows cmd colored ouput looks weird

### ISSUE THREAD

**Issue by twiese99** [twiese99/tic-tac-toe-java#7]
![image](https://user-images.githubusercontent.com/38278057/111657980-3b408000-880c-11eb-8778-1a2592e5f9ad.png)

**Comment by Tails32** [comment]
Use Windows Terminal or PowerShell instead. The command line is basically deprecated. I would recommend to not put too much effort into this, if any.

https://github.com/microsoft/terminal
https://aka.ms/terminal

**Comment by twiese99** [comment]
No change, as discussed
