### ISSUE TITLE
Update class diagram to match actual implementation

### ISSUE THREAD

**Issue by Tails32** [twiese99/tic-tac-toe-java#8]
We should maybe update the class diagram since we made quite a few changes to the structure of the project. Do you still have the source file for the diagram, @twiese99?

**Comment by twiese99** [comment]
I've never had the source files for the class diagram. Maybe @LukeBu95 or @JannisT13 can help us out.

**Comment by Tails32** [comment]
If not, someone could recreate it from scratch in draw.io but this is of course optional. Treat this task as low priority and a nice to have for the presentation tomorrow.

**Comment by Tails32** [comment]
Updated by @LukeBu95, changes of cleanup added by me.

see https://github.com/twiese99/tic-tac-toe-java/commit/24cc7d2d61f92f555f55e81a061d6d98bbbb5d85
