### ISSUE TITLE
Improvements for Code Cleanup

### ISSUE THREAD

**Issue by Tails32** [twiese99/tic-tac-toe-java#9]
There are multiple improvements of which most are suggestions from #6. Will make a list here tomorrow.

Work is to be done in: [refactoring-code-cleanup](https://github.com/twiese99/tic-tac-toe-java/tree/refactoring-code-cleanup) 

- [x] create Resources.java (see [here](https://github.com/twiese99/tic-tac-toe-java/pull/6#issuecomment-802030466))
- [x] [Context.java final properties](https://github.com/twiese99/tic-tac-toe-java/pull/6#discussion_r596973646)
- [x] [Context.java rename s to state](https://github.com/twiese99/tic-tac-toe-java/pull/6#discussion_r596975650)
- [x] [Turn.java reduce IF-ELSE nesting](https://github.com/twiese99/tic-tac-toe-java/pull/6#discussion_r596984243)
- [x] [Turn.java improve code segmentation by creating methods](https://github.com/twiese99/tic-tac-toe-java/pull/6#discussion_r596984243)

**Comment by Tails32** [comment]
@twiese99 Could you reduce the IF-ELSE nesting as you see fit? I already finished the other improvements. Since it was your suggestion, I think it'd be best if you did the changes you imagined by yourself.

**Comment by twiese99** [comment]
I take care of it and commit it to the branch "refactoring-code-cleanup"
